### ISSUE TITLE
something is wrong with the controller

### ISSUE THREAD

**Issue by LordPh** [Jire/Abendigo-Controller#5]
This error pops up when i open the controller (and yes,i did run the driver before the controller)
Thank you!You did a great job so far,keep up the good work! 👍 
I have been using abendigo for 2 and a half months

Exception in thread "main" java.net.ConnectException: Connection refused: no further information: localhost/127.0.0.1:58585
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:323)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:588)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Jire** [comment]
https://github.com/Jire/Abendigo/blob/master/src/main/kotlin/org/abendigo/Abendigo.kt#L27

**Comment by Charisma3** [comment]
how exactly should I change my file to enable it? Tysm!

**Comment by Jire** [comment]
Remove the `//` in front of `Server.bind().syncUninterruptibly()` :smile:

**Comment by collencream** [comment]
where is the file and how to open it to change the script?

**Comment by LordPh** [comment]
removing the // is not working

**Comment by FluffyPro** [comment]
I use the edit and disable things, how to download that one? like fluffy patch and replace with ur version
